import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';

export interface BlogPost {
  id: string;
  title: string;
  content: string;
  excerpt?: string;
  slug: string;
  author_id?: string;
  keywords?: string[];
  meta_description?: string;
  published: boolean;
  featured_image_url?: string;
  read_time_minutes?: number;
  views: number;
  created_at: string;
  updated_at: string;
}

export const useBlogPosts = (published?: boolean) => {
  return useQuery({
    queryKey: ['blog-posts', published],
    queryFn: async () => {
      let query = supabase.from('blog_posts').select('*').order('created_at', { ascending: false });
      
      if (published !== undefined) {
        query = query.eq('published', published);
      }
      
      const { data, error } = await query;
      if (error) throw error;
      return data as BlogPost[];
    },
  });
};

export const useBlogPost = (slug: string) => {
  return useQuery({
    queryKey: ['blog-post', slug],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('blog_posts')
        .select('*')
        .eq('slug', slug)
        .eq('published', true)
        .single();
      
      if (error) throw error;
      
      // Increment view count
      await supabase
        .from('blog_posts')
        .update({ views: data.views + 1 })
        .eq('id', data.id);
      
      return data as BlogPost;
    },
    enabled: !!slug,
  });
};

export const useCreateBlogPost = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (blogPost: { title: string; content: string; excerpt?: string; keywords?: string[]; meta_description?: string; published?: boolean; featured_image_url?: string; read_time_minutes?: number; }) => {
      if (!user) throw new Error('User not authenticated');

      const { data, error } = await supabase
        .from('blog_posts')
        .insert({
          title: blogPost.title,
          content: blogPost.content,
          slug: '', // Will be auto-generated by trigger
          excerpt: blogPost.excerpt,
          keywords: blogPost.keywords,
          meta_description: blogPost.meta_description,
          published: blogPost.published || false,
          featured_image_url: blogPost.featured_image_url,
          read_time_minutes: blogPost.read_time_minutes,
          author_id: user.id,
        })
        .select()
        .single();

      if (error) throw error;
      return data as BlogPost;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-posts'] });
    },
  });
};

export const useUpdateBlogPost = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, updates }: { id: string; updates: Partial<BlogPost> }) => {
      const { data, error } = await supabase
        .from('blog_posts')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data as BlogPost;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-posts'] });
    },
  });
};

export const useDeleteBlogPost = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('blog_posts')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['blog-posts'] });
    },
  });
};