// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mccehajzdnpkpusffhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jY2VoYWp6ZG5wa3B1c2ZmaGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDg2MTQsImV4cCI6MjA2ODg4NDYxNH0.W3ZvDkGaw2riwKiA5WuHCoaAwOMAh9rsu6_5J_4ucJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});